[package]
authors = ["Aramis Razzaghipour <aramisnoah@gmail.com>"]
edition = "2018"
name = "flimflam-server"
version = "0.1.0"

[dependencies]
anyhow = "1.0.36"
flimflam-model = {path = "../flimflam-model"}
jsonl = "1.0.0"
parking_lot = "0.11.1"
